name: Release
on:
  push:
    paths-ignore:
      - "**/renovate.json"
      - README.md
    branches:
      - master
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Install npm dependencies
        run: npm install
      - name: Release
        run: npm semantic-release
